import { WaveParams, ParticleConfig, OptimizeConfig } from '../types/ascii';

interface ExportConfig {
  name: string;
  type: 'parametric' | 'custom';
  params?: WaveParams;
  customCode?: string;
  customPrepare?: string;
  particleConfig?: ParticleConfig;
  optimizeConfig?: OptimizeConfig;
  cols: number;
  rows: number;
  density: string;
  fps: number;
}

export function generateAstroComponent(cfg: ExportConfig): string {
  const renderFormula =
    cfg.type === 'custom' && cfg.customCode
      ? cfg.customCode
      : `// Parametric Wave Synthesizer
  let val = 0;
  const radialAmp = ${cfg.params?.radialAmp ?? 0.6};
  if (radialAmp !== 0) {
    val += Math.sin(dist * ${cfg.params?.radialFreq ?? 0.12} - time * ${cfg.params?.radialSpeed ?? 1.0}) * radialAmp;
  }
  const xAmp = ${cfg.params?.xAmp ?? 0.2};
  if (xAmp !== 0) {
    val += Math.cos(dx * ${cfg.params?.xFreq ?? 0.08} + time * ${cfg.params?.xSpeed ?? 0.5}) * xAmp;
  }
  const yAmp = ${cfg.params?.yAmp ?? 0.2};
  if (yAmp !== 0) {
    val += Math.sin(dy * ${cfg.params?.yFreq ?? 0.08} + time * ${cfg.params?.ySpeed ?? 0.5}) * yAmp;
  }
  const spiralAmp = ${cfg.params?.spiralAmp ?? 0.0};
  if (spiralAmp !== 0) {
    val += Math.sin(angle * ${cfg.params?.spiralArms ?? 3} - time * ${cfg.params?.spiralSpeed ?? 2.0} + dist * 0.1) * spiralAmp;
  }
  const tunnelAmp = ${cfg.params?.tunnelAmp ?? 0.0};
  if (tunnelAmp !== 0) {
    const safeDist = Math.max(0.01, dist + 4.0);
    val += Math.sin(${cfg.params?.tunnelPower ?? 40} / safeDist - time * ${cfg.params?.tunnelSpeed ?? 1.5}) * tunnelAmp;
  }
  const dualEmitterAmp = ${cfg.params?.dualEmitterAmp ?? 0.0};
  if (dualEmitterAmp !== 0) {
    const d1 = Math.hypot(dx - 25, dy - 10);
    const d2 = Math.hypot(dx + 25, dy + 10);
    val += ((Math.sin(d1 * 0.15 - time * 2.0) + Math.sin(d2 * 0.15 - time * 2.0)) * 0.5) * dualEmitterAmp;
  }
  return val * ${cfg.params?.contrast ?? 1.0} + ${cfg.params?.bias ?? 0.0};`;

  const prepareSnippet = cfg.customPrepare
    ? `
    prepare(time: number, cols: number, rows: number) {
      ${cfg.customPrepare}
    },`
    : '';

  const flowStrength = cfg.particleConfig?.flowStrength ?? 0.9;
  const swirlStrength = cfg.particleConfig?.swirlStrength ?? 0.6;
  const drag = cfg.particleConfig?.drag ?? 0.93;
  const lifespan = cfg.particleConfig?.lifespan ?? 1.8;
  const trailChars = cfg.particleConfig?.trailChars ?? '@#%*+=-:. ';
  const burstCount = cfg.particleConfig?.burstCount ?? 18;
  const burstSpeed = cfg.particleConfig?.burstSpeed ?? 1.4;

  return `---
// Generated by ASCII Animation Builder (ascii.pantoine.com)
// Animation: ${cfg.name}
---

<div
  id="ascii-hero-container"
  class="w-full h-full relative overflow-hidden bg-black flex items-center justify-center cursor-crosshair select-none"
>
  <pre
    id="ascii-hero"
    aria-hidden="true"
    class="font-mono text-emerald-400 font-normal leading-none tracking-normal text-[8px] md:text-[11px] whitespace-pre [font-variant-ligatures:none] [font-feature-settings:'liga'_0,'calt'_0]"
  ></pre>
</div>

<script>
  let frameId: number;
  let lastTime = 0;
  const FPS_LIMIT = ${cfg.fps || 30};
  const FRAME_MIN_TIME = 1000 / FPS_LIMIT;

  interface TrailPoint {
    x: number;
    y: number;
    age: number;
    char: string;
    vx?: number;
    vy?: number;
  }

  const animationContext: Record<string, any> = {};

  const animation = {
    name: "${cfg.name}",${prepareSnippet}
    render(x: number, y: number, time: number, dist: number, dx: number, dy: number, cols: number, rows: number, angle: number, ctx: any) {
      ${renderFormula}
    },
    sampleField(x: number, y: number, time: number, cols: number, rows: number, aspectRatio: number) {
      const cx = cols / 2;
      const cy = rows / 2;
      const dx = (x - cx) * aspectRatio;
      const dy = y - cy;
      const dist = Math.hypot(dx, dy);
      const angle = Math.atan2(dy, dx);
      return this.render(x, y, time, dist, dx, dy, cols, rows, angle, animationContext);
    },
    updatePoint(p: TrailPoint, time: number, cols: number, rows: number, aspectRatio: number, dt: number = 0.016) {
      const eps = 0.5;
      const fRight = this.sampleField(p.x + eps, p.y, time, cols, rows, aspectRatio);
      const fLeft = this.sampleField(p.x - eps, p.y, time, cols, rows, aspectRatio);
      const fDown = this.sampleField(p.x, p.y + eps, time, cols, rows, aspectRatio);
      const fUp = this.sampleField(p.x, p.y - eps, time, cols, rows, aspectRatio);

      const gradX = (fRight - fLeft) / (2 * eps);
      const gradY = (fDown - fUp) / (2 * eps);

      const forceX = -gradX * (${(flowStrength * 0.4).toFixed(3)});
      const forceY = -gradY * (${(flowStrength * 0.4).toFixed(3)});
      const swirlX = -gradY * (${(swirlStrength * 0.3).toFixed(3)});
      const swirlY = gradX * (${(swirlStrength * 0.3).toFixed(3)});
      const dtFactor = Math.min(3.0, Math.max(0.1, dt * 60));
      const dragFactor = Math.pow(${drag.toFixed(2)}, dtFactor);
      p.vx = ((p.vx || 0) + (forceX + swirlX) * dtFactor) * dragFactor;
      p.vy = ((p.vy || 0) + (forceY + swirlY) * dtFactor) * dragFactor;

      p.x += (p.vx || 0) * dtFactor;
      p.y += (p.vy || 0) * dtFactor;
      p.age -= dt / Math.max(0.1, ${lifespan.toFixed(1)});
    },
    getClickParticles(x: number, y: number): TrailPoint[] {
      const particles: TrailPoint[] = [];
      const chars = ${JSON.stringify(trailChars)};
      for (let i = 0; i < ${burstCount}; i++) {
        const angle = (i / ${burstCount}) * Math.PI * 2 + (Math.random() - 0.5) * 0.3;
        const speed = (0.5 + Math.random() * 0.9) * ${burstSpeed.toFixed(1)};
        particles.push({
          x,
          y,
          age: 1.0,
          char: chars[Math.floor(Math.random() * chars.length)] || '@',
          vx: Math.cos(angle) * speed,
          vy: Math.sin(angle) * speed,
        });
      }
      return particles;
    }
  };

  function initAsciiAnimation() {
    const canvas = document.getElementById("ascii-hero") as HTMLPreElement | null;
    const container = document.getElementById("ascii-hero-container");
    if (!canvas || !container) return;

    if (frameId) cancelAnimationFrame(frameId);

    const density = ${JSON.stringify(cfg.density)};
    const cols = ${cfg.cols};
    const rows = ${cfg.rows};
    const aspectRatio = ${cfg.params?.aspectRatio ?? 0.55};
    let time = 0;
    let isVisible = true;
    let observer: IntersectionObserver | null = null;

    const trailPoints: TrailPoint[] = [];
    const trailChars = ${JSON.stringify(trailChars)};

    const lines = new Array(rows);
    const lineBuffer = new Array(cols);
    const totalCells = cols * rows;
    const trailInfluenceBuffer = new Float32Array(totalCells);
    const trailCharAgeBuffer = new Float32Array(totalCells);
    const trailCharBuffer = new Array(totalCells).fill('');

    observer = new IntersectionObserver(([entry]) => {
      isVisible = entry.isIntersecting;
    }, { threshold: 0 });
    observer.observe(container);

    function addPoint(x: number, y: number, age = 1.0, vx = 0, vy = 0) {
      trailPoints.push({
        x,
        y,
        age,
        char: trailChars[Math.floor(Math.random() * trailChars.length)],
        vx,
        vy,
      });
      if (trailPoints.length > 250) trailPoints.shift();
    }

    container.addEventListener("mousemove", (e) => {
      const rect = canvas.getBoundingClientRect();
      const mouseX = ((e.clientX - rect.left) / rect.width) * cols;
      const mouseY = ((e.clientY - rect.top) / rect.height) * rows;
      if (mouseX >= 0 && mouseX < cols && mouseY >= 0 && mouseY < rows) {
        addPoint(mouseX, mouseY);
      }
    });

    container.addEventListener("mousedown", (e) => {
      const rect = canvas.getBoundingClientRect();
      const cx = ((e.clientX - rect.left) / rect.width) * cols;
      const cy = ((e.clientY - rect.top) / rect.height) * rows;
      const particles = animation.getClickParticles(cx, cy);
      particles.forEach((p) => addPoint(p.x, p.y, p.age, p.vx, p.vy));
    });

    function render(timestamp: number) {
      if (!isVisible) {
        frameId = requestAnimationFrame(render);
        return;
      }

      const elapsed = timestamp - lastTime;
      if (elapsed < FRAME_MIN_TIME) {
        frameId = requestAnimationFrame(render);
        return;
      }
      lastTime = timestamp;

      const cx = cols / 2;
      const cy = rows / 2;

      if (animation.prepare) {
        animation.prepare(time, cols, rows);
      }

      const dt = Math.min(0.1, elapsed / 1000);
      for (let i = 0; i < trailPoints.length; i++) {
        animation.updatePoint(trailPoints[i], time, cols, rows, aspectRatio, dt);
      }

      while (trailPoints.length > 0 && trailPoints[0].age <= 0) {
        trailPoints.shift();
      }

      const radiusSq = 2.5 * 2.5;
      const hasTrails = trailPoints.length > 0;

      // Spatial particle pre-rasterization
      if (hasTrails) {
        trailInfluenceBuffer.fill(0);
        trailCharAgeBuffer.fill(0);
        trailCharBuffer.fill('');

        const rx = Math.ceil(2.5 / Math.max(0.1, aspectRatio));
        for (let i = 0; i < trailPoints.length; i++) {
          const pt = trailPoints[i];
          if (pt.age <= 0) continue;

          const ix = Math.floor(pt.x);
          const iy = Math.floor(pt.y);
          if (ix >= 0 && ix < cols && iy >= 0 && iy < rows && pt.age > 0.05) {
            const cellIdx = iy * cols + ix;
            if (pt.age > trailCharAgeBuffer[cellIdx]) {
              trailCharAgeBuffer[cellIdx] = pt.age;
              trailCharBuffer[cellIdx] = pt.char;
            }
          }

          const minX = Math.max(0, Math.floor(pt.x - rx));
          const maxX = Math.min(cols - 1, Math.ceil(pt.x + rx));
          const minY = Math.max(0, Math.floor(pt.y - 3));
          const maxY = Math.min(rows - 1, Math.ceil(pt.y + 3));

          for (let y = minY; y <= maxY; y++) {
            const ady = Math.abs(y - pt.y);
            if (ady >= 2.5) continue;
            const rOffset = y * cols;

            for (let x = minX; x <= maxX; x++) {
              const adx = Math.abs(x - pt.x) * aspectRatio;
              if (adx >= 2.5) continue;
              const tdistSq = adx * adx + ady * ady;
              if (tdistSq < radiusSq) {
                trailInfluenceBuffer[rOffset + x] += (1 - Math.sqrt(tdistSq) / 2.5) * pt.age * 0.5;
              }
            }
          }
        }
      }

      for (let y = 0; y < rows; y++) {
        const dy = y - cy;
        const rowOffset = y * cols;

        for (let x = 0; x < cols; x++) {
          const dx = (x - cx) * aspectRatio;
          const dist = Math.hypot(dx, dy);
          const angle = Math.atan2(dy, dx);

          const animVal = animation.render(x, y, time, dist, dx, dy, cols, rows, angle, animationContext);
          const cellIdx = rowOffset + x;
          const trailInf = hasTrails ? trailInfluenceBuffer[cellIdx] : 0;

          let normalized = (animVal + 1) * 0.5 + trailInf;
          let charIndex = Math.floor(normalized * density.length);
          charIndex = Math.max(0, Math.min(density.length - 1, charIndex));

          let char = density[charIndex];
          if (hasTrails && trailCharBuffer[cellIdx]) {
            char = trailCharBuffer[cellIdx];
          }

          lineBuffer[x] = char;
        }
        lines[y] = lineBuffer.join('');
      }

      if (canvas) {
        canvas.textContent = lines.join('\\n');
      }

      time += 0.02 * ${(cfg.params?.timeSpeed ?? 1.0).toFixed(2)};
      frameId = requestAnimationFrame(render);
    }

    frameId = requestAnimationFrame(render);

    return () => {
      if (frameId) cancelAnimationFrame(frameId);
      if (observer) observer.disconnect();
    };
  }

  let cleanup: (() => void) | undefined;
  function start() {
    if (cleanup) cleanup();
    cleanup = initAsciiAnimation();
  }

  start();
  document.addEventListener("astro:before-swap", () => {
    if (cleanup) cleanup();
  });
  document.addEventListener("astro:after-swap", start);
</script>
`;
}

export function generateStandaloneHtml(cfg: ExportConfig): string {
  const astroCode = generateAstroComponent(cfg);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${cfg.name} - ASCII Animation</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #050505;
      color: #00ff66;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      overflow: hidden;
      font-family: monospace;
    }
    #ascii-hero-container {
      width: 100vw;
      height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: crosshair;
    }
    pre {
      font-family: 'JuliaMono', 'Noto Sans Mono', 'JetBrains Mono', 'DejaVu Sans Mono', ui-monospace, monospace;
      font-size: 10px;
      line-height: 10px;
      letter-spacing: 0px;
      word-spacing: 0px;
      user-select: none;
      white-space: pre;
      font-variant-ligatures: none;
      -webkit-font-variant-ligatures: none;
      font-feature-settings: "liga" 0, "calt" 0, "dlig" 0, "tnum" 1;
      font-variant-numeric: tabular-nums;
      text-rendering: geometricPrecision;
    }
  </style>
</head>
<body>
  <div id="ascii-hero-container">
    <pre id="ascii-hero"></pre>
  </div>

  <script>
  ${astroCode.substring(astroCode.indexOf('<script>') + 8, astroCode.lastIndexOf('</script>'))}
  </script>
</body>
</html>`;
}

export function generateAiPrompt(cfg: ExportConfig): string {
  const renderFormula =
    cfg.type === 'custom' && cfg.customCode
      ? cfg.customCode
      : `// Parametric Wave Synthesizer
  let val = 0;
  const radialAmp = ${cfg.params?.radialAmp ?? 0.6};
  if (radialAmp !== 0) {
    val += Math.sin(dist * ${cfg.params?.radialFreq ?? 0.12} - time * ${cfg.params?.radialSpeed ?? 1.0}) * radialAmp;
  }
  const xAmp = ${cfg.params?.xAmp ?? 0.2};
  if (xAmp !== 0) {
    val += Math.cos(dx * ${cfg.params?.xFreq ?? 0.08} + time * ${cfg.params?.xSpeed ?? 0.5}) * xAmp;
  }
  const yAmp = ${cfg.params?.yAmp ?? 0.2};
  if (yAmp !== 0) {
    val += Math.sin(dy * ${cfg.params?.yFreq ?? 0.08} + time * ${cfg.params?.ySpeed ?? 0.5}) * yAmp;
  }
  const spiralAmp = ${cfg.params?.spiralAmp ?? 0.0};
  if (spiralAmp !== 0) {
    val += Math.sin(angle * ${cfg.params?.spiralArms ?? 3} - time * ${cfg.params?.spiralSpeed ?? 2.0} + dist * 0.1) * spiralAmp;
  }
  const tunnelAmp = ${cfg.params?.tunnelAmp ?? 0.0};
  if (tunnelAmp !== 0) {
    const safeDist = Math.max(0.01, dist + 4.0);
    val += Math.sin(${cfg.params?.tunnelPower ?? 40} / safeDist - time * ${cfg.params?.tunnelSpeed ?? 1.5}) * tunnelAmp;
  }
  const dualEmitterAmp = ${cfg.params?.dualEmitterAmp ?? 0.0};
  if (dualEmitterAmp !== 0) {
    const d1 = Math.hypot(dx - 25, dy - 10);
    const d2 = Math.hypot(dx + 25, dy + 10);
    val += ((Math.sin(d1 * 0.15 - time * 2.0) + Math.sin(d2 * 0.15 - time * 2.0)) * 0.5) * dualEmitterAmp;
  }
  return val * ${cfg.params?.contrast ?? 1.0} + ${cfg.params?.bias ?? 0.0};`;

  const prepareSnippet = cfg.customPrepare
    ? `\n--- OPTIONAL FRAME PREPARATION (ctx.prepare) ---\n${cfg.customPrepare}\n`
    : '';

  const flowStrength = cfg.particleConfig?.flowStrength ?? 0.9;
  const swirlStrength = cfg.particleConfig?.swirlStrength ?? 0.6;
  const drag = cfg.particleConfig?.drag ?? 0.93;
  const lifespan = cfg.particleConfig?.lifespan ?? 1.8;
  const trailChars = cfg.particleConfig?.trailChars ?? '@#%*+=-:. ';
  const burstCount = cfg.particleConfig?.burstCount ?? 18;
  const burstSpeed = cfg.particleConfig?.burstSpeed ?? 1.4;

  const targetFps = cfg.optimizeConfig?.targetFps ?? cfg.fps ?? 60;
  const targetFpsDesc = targetFps === 0 ? 'Uncapped / VSync (~60-120 FPS)' : `${targetFps} FPS (Frame interval: ${(1000 / targetFps).toFixed(1)}ms)`;
  const pauseWhenHidden = cfg.optimizeConfig?.pauseWhenHidden ?? true;
  const idleThrottle = cfg.optimizeConfig?.idleThrottle ?? false;

  return `================================================================================
TASK: REPRODUCE THIS EXACT INTERACTIVE ASCII ANIMATION
================================================================================

You are an expert creative technologist, shader developer, and front-end engineer.
Your task is to reproduce this exact interactive mathematical ASCII wave animation for the user.

IMPORTANT INSTRUCTION FOR THE AI:
Before generating the final implementation code, ASK THE USER where and in what environment they want to implement this animation (for example: React component, Next.js, Astro, Vue, Svelte, standalone HTML/JS/CSS, Canvas/WebGL, or Terminal script), and if they have any specific layout, container, or styling requirements. Once the user replies with their target environment, generate the complete, self-contained, drop-in code.

All mathematical formulas, physics constants, performance optimization settings, ASCII density mapping, and typography rules are specified below.

================================================================================
1. ANIMATION SPECIFICATION & OPTIMIZATION SETTINGS
================================================================================
- Animation Name: "${cfg.name}"
- Grid Resolution: ${cfg.cols} columns × ${cfg.rows} rows (${cfg.cols * cfg.rows} total cells)
- Target Framerate: ${targetFpsDesc}
- Smart Throttling (Pause when Hidden): ${pauseWhenHidden ? 'ENABLED (Pause requestAnimationFrame loop when document.hidden or off-screen)' : 'DISABLED'}
- Smart Throttling (Idle Throttle): ${idleThrottle ? 'ENABLED (Drop framerate to 12 FPS when user is idle for >4 seconds)' : 'DISABLED'}
- Active Density Charset: "${cfg.density}" (Length: ${cfg.density.length} glyphs, sorted dark to light)
- Aspect Compensation Factor (Global Dynamics): ${cfg.params?.aspectRatio ?? 0.55}
- Theme Aesthetic: Phosphor terminal glow (#00ff66 or custom accent) on deep dark (#050505) background
- Interactivity: Cursor movement illuminates the wave field; mouse clicks trigger radial particle bursts.

================================================================================
2. EXACT MATHEMATICAL FORMULA & EVALUATION
================================================================================
For each cell at integer coordinates (x, y) with center (cx = cols / 2, cy = rows / 2) at time (t in seconds):

Geometry setup:
  dx = (x - cx) * ${cfg.params?.aspectRatio ?? 0.55}
  dy = y - cy
  dist = Math.hypot(dx, dy)
  angle = Math.atan2(dy, dx)

Core evaluation formula:
--------------------------------------------------------------------------------
${renderFormula}
--------------------------------------------------------------------------------
${prepareSnippet}
Parameter breakdown:
- Time Speed Multiplier: ${cfg.params?.timeSpeed ?? 1.0}
- Aspect Compensation (Global Dynamics): ${cfg.params?.aspectRatio ?? 0.55}
- Contrast: ${cfg.params?.contrast ?? 1.0} | Bias: ${cfg.params?.bias ?? 0.0}
- Radial Wave: Amp=${cfg.params?.radialAmp ?? 0}, Freq=${cfg.params?.radialFreq ?? 0}, Speed=${cfg.params?.radialSpeed ?? 0}
- Harmonic Ripple: Amp=${cfg.params?.radial2Amp ?? 0}, Freq=${cfg.params?.radial2Freq ?? 0}, Speed=${cfg.params?.radial2Speed ?? 0}
- Directional X: Amp=${cfg.params?.xAmp ?? 0}, Freq=${cfg.params?.xFreq ?? 0}, Speed=${cfg.params?.xSpeed ?? 0}
- Directional Y: Amp=${cfg.params?.yAmp ?? 0}, Freq=${cfg.params?.yFreq ?? 0}, Speed=${cfg.params?.ySpeed ?? 0}
- Diagonal (X+Y): Amp=${cfg.params?.diagAmp ?? 0}, Freq=${cfg.params?.diagFreq ?? 0}, Speed=${cfg.params?.diagSpeed ?? 0}
- Spiral Vortex: Amp=${cfg.params?.spiralAmp ?? 0}, Arms=${cfg.params?.spiralArms ?? 0}, Speed=${cfg.params?.spiralSpeed ?? 0}, Twist=${cfg.params?.spiralTwist ?? 0}
- Depth Tunnel: Amp=${cfg.params?.tunnelAmp ?? 0}, Power=${cfg.params?.tunnelPower ?? 0}, Speed=${cfg.params?.tunnelSpeed ?? 0}
- Concentric Rings: Amp=${cfg.params?.ringsAmp ?? 0}, Radius=${cfg.params?.ringsRadius ?? 0}, Speed=${cfg.params?.ringsSpeed ?? 0}, Count=${cfg.params?.ringsCount ?? 0}
- Dual Emitters: Amp=${cfg.params?.dualEmitterAmp ?? 0}, Spacing=${cfg.params?.dualEmitterSpacing ?? 0}, Freq=${cfg.params?.dualEmitterFreq ?? 0}, Speed=${cfg.params?.dualEmitterSpeed ?? 0}
- Starfield Sparkle: Intensity=${cfg.params?.starfieldIntensity ?? 0}

================================================================================
3. PARTICLE PHYSICS & MOUSE TRAIL
================================================================================
- Flow Field Strength: ${flowStrength}
- Swirl Force Strength: ${swirlStrength}
- Particle Drag Factor: ${drag}
- Lifespan: ${lifespan}s
- Burst Count on Click: ${burstCount}
- Burst Speed: ${burstSpeed}
- Trail Glyphs: ${JSON.stringify(trailChars)}

Gradient-based vector forces on particle (px, py) at time t:
  fRight = sampleField(px + 0.5, py, t)
  fLeft  = sampleField(px - 0.5, py, t)
  fDown  = sampleField(px, py + 0.5, t)
  fUp    = sampleField(px, py - 0.5, t)
  gradX  = (fRight - fLeft)
  gradY  = (fDown - fUp)
  forceX = -gradX * ${(flowStrength * 0.4).toFixed(3)}
  forceY = -gradY * ${(flowStrength * 0.4).toFixed(3)}
  swirlX = -gradY * ${(swirlStrength * 0.3).toFixed(3)}
  swirlY =  gradX * ${(swirlStrength * 0.3).toFixed(3)}
  vx = (vx + (forceX + swirlX) * dtFactor) * drag
  vy = (vy + (forceY + swirlY) * dtFactor) * drag
  px += vx * dtFactor
  py += vy * dtFactor

================================================================================
4. ASCII TERMINAL RENDERING, CSS & PERFORMANCE CONSTRAINTS
================================================================================
1. Aspect Compensation (Global Dynamics):
   - Monospace font characters are rectangular rather than square (standard monospace font cells are ~6px wide × 10px high, representing a ~0.55-0.6 ratio).
   - To compensate for character cell geometry or achieve custom geometric stretching, the animation uses the user-configured Aspect Compensation factor from Global Dynamics (active value: ${cfg.params?.aspectRatio ?? 0.55}).
   - Always scale horizontal distance by this exact parameter when computing distance and angle:
       dx = (x - cx) * ${cfg.params?.aspectRatio ?? 0.55}
       dy = y - cy
       dist = Math.hypot(dx, dy)
       angle = Math.atan2(dy, dx)

2. Density & Luminance Mapping:
   - Normalize mathematical value to [0.0, 1.0]: normalized = (val + 1.0) * 0.5 + trailInfluence
   - Map to charset index: charIndex = Math.floor(normalized * charset.length)
   - Clamp bounds: charIndex = Math.max(0, Math.min(charset.length - 1, charIndex))
   - Resulting glyph: charset[charIndex]

3. Font & CSS Rules (MANDATORY):
   - Font stack: 'JuliaMono', 'Noto Sans Mono', 'JetBrains Mono', 'DejaVu Sans Mono', ui-monospace, SFMono-Regular, monospace
   - Mandatory CSS properties:
     white-space: pre;
     line-height: 1.0;
     letter-spacing: 0px;
     word-spacing: 0px;
     font-variant-ligatures: none;
     -webkit-font-variant-ligatures: none;
     font-feature-settings: "liga" 0, "calt" 0, "dlig" 0, "tnum" 1;
     font-variant-numeric: tabular-nums;
     text-rendering: geometricPrecision;
   - Disabling ligatures and using tabular-nums is strictly required so combinations like '->', '==', or '//' do NOT merge into single glyphs and all Unicode symbols preserve identical advance widths.

4. Performance & Runtime Optimization:
   - Target Framerate: Implement FPS limiter for ${targetFpsDesc}.
   ${pauseWhenHidden ? '- Pause when Inactive: Use IntersectionObserver and document.hidden to pause requestAnimationFrame when the element or tab is not visible (0% CPU idle).' : ''}
   ${idleThrottle ? '- Idle Throttling: When no user interaction (mousemove/touch) has occurred for >4s, throttle to 12 FPS to conserve device battery.' : ''}
   - Single Buffer DOM Writes: Render the complete grid into a single string joined by '\\n' (e.g. lines.join('\\n')) and update <pre>.textContent once per frame. Do NOT create separate DOM nodes per character.

================================================================================
5. INSTRUCTIONS FOR THE AI ASSISTANT
================================================================================
1. STEP 1: Ask the user which framework or environment they want this implemented in (e.g. React/Next.js, Vue, Svelte, Astro, HTML/JS/CSS, or Terminal script).
2. STEP 2: Upon user confirmation, generate the complete, self-contained, drop-in code:
   - Faithfully implement the mathematical formula, harmonics, and physics specified above.
   - Implement the configured resolution (${cfg.cols}x${cfg.rows}) and framerate limiter (${targetFpsDesc}).
   - Implement container zoom / auto-fitting so it scales seamlessly to fill its viewport.
================================================================================
`;
}
