import { WaveParams, ParticleConfig } from '../types/ascii';

interface ExportConfig {
  name: string;
  type: 'parametric' | 'custom';
  params?: WaveParams;
  customCode?: string;
  customPrepare?: string;
  particleConfig?: ParticleConfig;
  cols: number;
  rows: number;
  density: string;
  fps: number;
}

export function generateAstroComponent(cfg: ExportConfig): string {
  const renderFormula =
    cfg.type === 'custom' && cfg.customCode
      ? cfg.customCode
      : `// Parametric Wave Synthesizer
  let val = 0;
  const radialAmp = ${cfg.params?.radialAmp ?? 0.6};
  if (radialAmp !== 0) {
    val += Math.sin(dist * ${cfg.params?.radialFreq ?? 0.12} - time * ${cfg.params?.radialSpeed ?? 1.0}) * radialAmp;
  }
  const xAmp = ${cfg.params?.xAmp ?? 0.2};
  if (xAmp !== 0) {
    val += Math.cos(dx * ${cfg.params?.xFreq ?? 0.08} + time * ${cfg.params?.xSpeed ?? 0.5}) * xAmp;
  }
  const yAmp = ${cfg.params?.yAmp ?? 0.2};
  if (yAmp !== 0) {
    val += Math.sin(dy * ${cfg.params?.yFreq ?? 0.08} + time * ${cfg.params?.ySpeed ?? 0.5}) * yAmp;
  }
  const spiralAmp = ${cfg.params?.spiralAmp ?? 0.0};
  if (spiralAmp !== 0) {
    val += Math.sin(angle * ${cfg.params?.spiralArms ?? 3} - time * ${cfg.params?.spiralSpeed ?? 2.0} + dist * 0.1) * spiralAmp;
  }
  const tunnelAmp = ${cfg.params?.tunnelAmp ?? 0.0};
  if (tunnelAmp !== 0) {
    const safeDist = Math.max(0.01, dist + 4.0);
    val += Math.sin(${cfg.params?.tunnelPower ?? 40} / safeDist - time * ${cfg.params?.tunnelSpeed ?? 1.5}) * tunnelAmp;
  }
  const dualEmitterAmp = ${cfg.params?.dualEmitterAmp ?? 0.0};
  if (dualEmitterAmp !== 0) {
    const d1 = Math.hypot(dx - 25, dy - 10);
    const d2 = Math.hypot(dx + 25, dy + 10);
    val += ((Math.sin(d1 * 0.15 - time * 2.0) + Math.sin(d2 * 0.15 - time * 2.0)) * 0.5) * dualEmitterAmp;
  }
  return val * ${cfg.params?.contrast ?? 1.0} + ${cfg.params?.bias ?? 0.0};`;

  const prepareSnippet = cfg.customPrepare
    ? `
    prepare(time: number, cols: number, rows: number) {
      ${cfg.customPrepare}
    },`
    : '';

  const flowStrength = cfg.particleConfig?.flowStrength ?? 0.9;
  const swirlStrength = cfg.particleConfig?.swirlStrength ?? 0.6;
  const drag = cfg.particleConfig?.drag ?? 0.93;
  const lifespan = cfg.particleConfig?.lifespan ?? 1.8;
  const trailChars = cfg.particleConfig?.trailChars ?? '@#%*+=-:. ';
  const burstCount = cfg.particleConfig?.burstCount ?? 18;
  const burstSpeed = cfg.particleConfig?.burstSpeed ?? 1.4;

  return `---
// Generated by ASCII Animation Builder (ascii.pantoine.com)
// Animation: ${cfg.name}
---

<div
  id="ascii-hero-container"
  class="w-full h-full relative overflow-hidden bg-black flex items-center justify-center cursor-crosshair select-none"
>
  <pre
    id="ascii-hero"
    aria-hidden="true"
    class="font-mono text-emerald-400 font-normal leading-none tracking-normal text-[8px] md:text-[11px] whitespace-pre [font-variant-ligatures:none] [font-feature-settings:'liga'_0,'calt'_0]"
  ></pre>
</div>

<script>
  let frameId: number;
  let lastTime = 0;
  const FPS_LIMIT = ${cfg.fps || 30};
  const FRAME_MIN_TIME = 1000 / FPS_LIMIT;

  interface TrailPoint {
    x: number;
    y: number;
    age: number;
    char: string;
    vx?: number;
    vy?: number;
  }

  const animationContext: Record<string, any> = {};

  const animation = {
    name: "${cfg.name}",${prepareSnippet}
    render(x: number, y: number, time: number, dist: number, dx: number, dy: number, cols: number, rows: number, angle: number, ctx: any) {
      ${renderFormula}
    },
    sampleField(x: number, y: number, time: number, cols: number, rows: number, aspectRatio: number) {
      const cx = cols / 2;
      const cy = rows / 2;
      const dx = (x - cx) * aspectRatio;
      const dy = y - cy;
      const dist = Math.hypot(dx, dy);
      const angle = Math.atan2(dy, dx);
      return this.render(x, y, time, dist, dx, dy, cols, rows, angle, animationContext);
    },
    updatePoint(p: TrailPoint, time: number, cols: number, rows: number, aspectRatio: number, dt: number = 0.016) {
      const eps = 0.5;
      const fRight = this.sampleField(p.x + eps, p.y, time, cols, rows, aspectRatio);
      const fLeft = this.sampleField(p.x - eps, p.y, time, cols, rows, aspectRatio);
      const fDown = this.sampleField(p.x, p.y + eps, time, cols, rows, aspectRatio);
      const fUp = this.sampleField(p.x, p.y - eps, time, cols, rows, aspectRatio);

      const gradX = (fRight - fLeft) / (2 * eps);
      const gradY = (fDown - fUp) / (2 * eps);

      const forceX = -gradX * (${(flowStrength * 0.4).toFixed(3)});
      const forceY = -gradY * (${(flowStrength * 0.4).toFixed(3)});
      const swirlX = -gradY * (${(swirlStrength * 0.3).toFixed(3)});
      const swirlY = gradX * (${(swirlStrength * 0.3).toFixed(3)});
      const dtFactor = Math.min(3.0, Math.max(0.1, dt * 60));
      const dragFactor = Math.pow(${drag.toFixed(2)}, dtFactor);
      p.vx = ((p.vx || 0) + (forceX + swirlX) * dtFactor) * dragFactor;
      p.vy = ((p.vy || 0) + (forceY + swirlY) * dtFactor) * dragFactor;

      p.x += (p.vx || 0) * dtFactor;
      p.y += (p.vy || 0) * dtFactor;
      p.age -= dt / Math.max(0.1, ${lifespan.toFixed(1)});
    },
    getClickParticles(x: number, y: number): TrailPoint[] {
      const particles: TrailPoint[] = [];
      const chars = ${JSON.stringify(trailChars)};
      for (let i = 0; i < ${burstCount}; i++) {
        const angle = (i / ${burstCount}) * Math.PI * 2 + (Math.random() - 0.5) * 0.3;
        const speed = (0.5 + Math.random() * 0.9) * ${burstSpeed.toFixed(1)};
        particles.push({
          x,
          y,
          age: 1.0,
          char: chars[Math.floor(Math.random() * chars.length)] || '@',
          vx: Math.cos(angle) * speed,
          vy: Math.sin(angle) * speed,
        });
      }
      return particles;
    }
  };

  function initAsciiAnimation() {
    const canvas = document.getElementById("ascii-hero") as HTMLPreElement | null;
    const container = document.getElementById("ascii-hero-container");
    if (!canvas || !container) return;

    if (frameId) cancelAnimationFrame(frameId);

    const density = ${JSON.stringify(cfg.density)};
    const cols = ${cfg.cols};
    const rows = ${cfg.rows};
    const aspectRatio = ${cfg.params?.aspectRatio ?? 0.55};
    let time = 0;
    let isVisible = true;

    const trailPoints: TrailPoint[] = [];
    const trailChars = ${JSON.stringify(trailChars)};

    const observer = new IntersectionObserver(([entry]) => {
      isVisible = entry.isIntersecting;
    }, { threshold: 0 });
    observer.observe(container);

    function addPoint(x: number, y: number, age = 1.0, vx = 0, vy = 0) {
      trailPoints.push({
        x,
        y,
        age,
        char: trailChars[Math.floor(Math.random() * trailChars.length)],
        vx,
        vy,
      });
      if (trailPoints.length > 250) trailPoints.shift();
    }

    container.addEventListener("mousemove", (e) => {
      const rect = canvas.getBoundingClientRect();
      const mouseX = ((e.clientX - rect.left) / rect.width) * cols;
      const mouseY = ((e.clientY - rect.top) / rect.height) * rows;
      if (mouseX >= 0 && mouseX < cols && mouseY >= 0 && mouseY < rows) {
        addPoint(mouseX, mouseY);
      }
    });

    container.addEventListener("mousedown", (e) => {
      const rect = canvas.getBoundingClientRect();
      const cx = ((e.clientX - rect.left) / rect.width) * cols;
      const cy = ((e.clientY - rect.top) / rect.height) * rows;
      const particles = animation.getClickParticles(cx, cy);
      particles.forEach((p) => addPoint(p.x, p.y, p.age, p.vx, p.vy));
    });

    function render(timestamp: number) {
      if (!isVisible) {
        frameId = requestAnimationFrame(render);
        return;
      }

      const elapsed = timestamp - lastTime;
      if (elapsed < FRAME_MIN_TIME) {
        frameId = requestAnimationFrame(render);
        return;
      }
      lastTime = timestamp;

      const cx = cols / 2;
      const cy = rows / 2;

      if (animation.prepare) {
        animation.prepare(time, cols, rows);
      }

      const dt = Math.min(0.1, elapsed / 1000);
      for (let i = 0; i < trailPoints.length; i++) {
        animation.updatePoint(trailPoints[i], time, cols, rows, aspectRatio, dt);
      }

      while (trailPoints.length > 0 && trailPoints[0].age <= 0) {
        trailPoints.shift();
      }

      const grid: string[][] = [];
      const radiusSq = 2.5 * 2.5;

      for (let y = 0; y < rows; y++) {
        grid[y] = [];
        const dy = y - cy;
        for (let x = 0; x < cols; x++) {
          const dx = (x - cx) * aspectRatio;
          const dist = Math.hypot(dx, dy);
          const angle = Math.atan2(dy, dx);

          const animVal = animation.render(x, y, time, dist, dx, dy, cols, rows, angle, animationContext);

          let trailInf = 0;
          for (let p = 0; p < trailPoints.length; p++) {
            const pt = trailPoints[p];
            const adx = Math.abs(x - pt.x) * aspectRatio;
            const ady = Math.abs(y - pt.y);
            if (adx < 2.5 && ady < 2.5) {
              const tdistSq = adx * adx + ady * ady;
              if (tdistSq < radiusSq) {
                trailInf += (1 - Math.sqrt(tdistSq) / 2.5) * pt.age * 0.5;
              }
            }
          }

          let normalized = (animVal + 1) * 0.5 + trailInf;
          let charIndex = Math.floor(normalized * density.length);
          charIndex = Math.max(0, Math.min(density.length - 1, charIndex));
          grid[y][x] = density[charIndex];
        }
      }

      for (let p = 0; p < trailPoints.length; p++) {
        const pt = trailPoints[p];
        const px = Math.floor(pt.x);
        const py = Math.floor(pt.y);
        if (px >= 0 && px < cols && py >= 0 && py < rows) {
          if (Math.random() < pt.age * 0.5) {
            grid[py][px] = pt.char;
          }
        }
      }

      if (canvas) {
        canvas.textContent = grid.map((r) => r.join("")).join("\\n");
      }

      time += 0.02 * ${(cfg.params?.timeSpeed ?? 1.0).toFixed(2)};
      frameId = requestAnimationFrame(render);
    }

    frameId = requestAnimationFrame(render);
  }

  initAsciiAnimation();
  document.addEventListener("astro:after-swap", initAsciiAnimation);
</script>
`;
}

export function generateStandaloneHtml(cfg: ExportConfig): string {
  const astroCode = generateAstroComponent(cfg);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${cfg.name} - ASCII Animation</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #050505;
      color: #00ff66;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      overflow: hidden;
      font-family: monospace;
    }
    #ascii-hero-container {
      width: 100vw;
      height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: crosshair;
    }
    pre {
      font-family: 'JetBrains Mono', 'Fira Code', ui-monospace, monospace;
      font-size: 10px;
      line-height: 10px;
      letter-spacing: 0px;
      user-select: none;
      white-space: pre;
      font-variant-ligatures: none;
      -webkit-font-variant-ligatures: none;
      font-feature-settings: "liga" 0, "calt" 0, "dlig" 0;
    }
  </style>
</head>
<body>
  <div id="ascii-hero-container">
    <pre id="ascii-hero"></pre>
  </div>

  <script>
  ${astroCode.substring(astroCode.indexOf('<script>') + 8, astroCode.lastIndexOf('</script>'))}
  </script>
</body>
</html>`;
}
