import { ModelConfig, ModelViewConfig, ModelPreset } from '../types/ascii';
import { CHARSETS } from './renderer';

export const DEFAULT_MODEL_CONFIG: ModelConfig = {
  sourceType: 'preset',
  modelId: 'torus-knot',
  scale: 1.0,
  scaleX: 1.0,
  scaleY: 1.0,
  scaleZ: 1.0,
  offsetX: 0,
  offsetY: 0,
  offsetZ: 0,
  normalizeSize: true,
  autoCenter: true,
  flatShading: false,
  wireframe: false,
  doubleSided: false,
  invertNormals: false,
};

export const DEFAULT_MODEL_VIEW_CONFIG: ModelViewConfig = {
  shadingMode: 'shaded',
  autoRotate: true,
  autoRotateSpeedX: 0.35,
  autoRotateSpeedY: 0.75,
  autoRotateSpeedZ: 0.15,
  manualRotationX: 0.2,
  manualRotationY: 0.0,
  manualRotationZ: 0.0,
  wobbleSpeed: 0.0,
  wobbleAmp: 0.0,
  lightAngleX: 45,
  lightAngleY: 35,
  lightIntensity: 1.25,
  ambientLight: 0.35,
  specularIntensity: 1.1,
  contrast: 1.35,
  brightness: 0.0,
  invert: false,
  edgeThreshold: 0.18,
  edgeWeight: 0.0,
  cameraDistance: 3.2,
  fov: 45,
  isOrthographic: false,
};

export const MODEL_PRESETS: ModelPreset[] = [
  {
    id: 'torus-knot',
    name: 'Torus Knot',
    description: 'Hypnotic (2,3) mathematical parametric knot',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'torus-knot',
      scale: 1.05,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.35,
      autoRotateSpeedY: 0.75,
      autoRotateSpeedZ: 0.15,
      contrast: 1.4,
    },
    theme: 'cyan',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'skull',
    name: 'Skull',
    description: '3D anatomical human skull OBJ model',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'skull',
      scale: 1.05,
      flatShading: false,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotate: true,
      autoRotateSpeedX: 0.0,
      autoRotateSpeedY: 0.0,
      autoRotateSpeedZ: -0.3,
      manualRotationX: -1.8326, // -105 deg
      manualRotationY: 0.0175,  // 1 deg
      manualRotationZ: 0.0,
      contrast: 1.45,
      cameraDistance: 3.2,
    },
    theme: 'blood',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'cube',
    name: 'Cube',
    description: 'Geometric 3D cube with clean faceted surface normals',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'cube',
      scale: 1.0,
      flatShading: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.4,
      autoRotateSpeedY: 0.6,
      autoRotateSpeedZ: 0.2,
      manualRotationX: 0.35,
      contrast: 1.45,
      cameraDistance: 3.2,
    },
    theme: 'green',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'cylinder',
    name: 'Cylinder',
    description: 'Smooth cylindrical primitive with top and bottom caps',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'cylinder',
      scale: 1.0,
      flatShading: false,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.25,
      autoRotateSpeedY: 0.7,
      autoRotateSpeedZ: 0.1,
      manualRotationX: 0.4,
      contrast: 1.4,
      cameraDistance: 3.3,
    },
    theme: 'amber',
    densityCharset: CHARSETS[0].chars,
  },
];
