import { ModelConfig, ModelViewConfig, ModelPreset } from '../types/ascii';
import { CHARSETS } from './renderer';

export const DEFAULT_MODEL_CONFIG: ModelConfig = {
  sourceType: 'preset',
  modelId: 'torus-knot',
  scale: 1.0,
  scaleX: 1.0,
  scaleY: 1.0,
  scaleZ: 1.0,
  offsetX: 0,
  offsetY: 0,
  offsetZ: 0,
  normalizeSize: true,
  autoCenter: true,
  flatShading: false,
  wireframe: false,
  doubleSided: false,
  invertNormals: false,
};

export const DEFAULT_MODEL_VIEW_CONFIG: ModelViewConfig = {
  shadingMode: 'shaded',
  autoRotate: true,
  autoRotateSpeedX: 0.35,
  autoRotateSpeedY: 0.75,
  autoRotateSpeedZ: 0.15,
  manualRotationX: 0.2,
  manualRotationY: 0.0,
  manualRotationZ: 0.0,
  wobbleSpeed: 0.0,
  wobbleAmp: 0.0,
  lightAngleX: 45,
  lightAngleY: 35,
  lightIntensity: 1.25,
  ambientLight: 0.35,
  specularIntensity: 1.1,
  contrast: 1.35,
  brightness: 0.0,
  invert: false,
  edgeThreshold: 0.18,
  edgeWeight: 0.0,
  cameraDistance: 3.2,
  fov: 45,
  isOrthographic: false,
};

export const MODEL_PRESETS: ModelPreset[] = [
  {
    id: 'torus-knot',
    name: 'Torus Knot',
    description: 'Hypnotic (2,3) mathematical parametric knot',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'torus-knot',
      scale: 1.05,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.35,
      autoRotateSpeedY: 0.75,
      autoRotateSpeedZ: 0.15,
      contrast: 1.4,
    },
    theme: 'cyan',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'teapot',
    name: 'Utah Teapot',
    description: 'The legendary standard computer graphics benchmark model',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'teapot',
      scale: 1.1,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.1,
      autoRotateSpeedY: 0.65,
      autoRotateSpeedZ: 0.0,
      manualRotationX: 0.25,
      contrast: 1.3,
      cameraDistance: 3.1,
    },
    theme: 'amber',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'skull',
    name: 'Cyber Skull',
    description: 'Stylized low-poly cyber cranium with high-contrast outlines',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'skull',
      scale: 1.15,
      flatShading: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'outline',
      autoRotateSpeedX: 0.1,
      autoRotateSpeedY: 0.6,
      autoRotateSpeedZ: 0.0,
      manualRotationX: 0.15,
      edgeThreshold: 0.15,
      edgeWeight: 1.8,
      contrast: 1.6,
    },
    theme: 'blood',
    densityCharset: CHARSETS[1].chars,
  },
  {
    id: 'dna',
    name: 'DNA Double Helix',
    description: 'Biochemical spiraling genetic ladder with base pair rungs',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'dna',
      scale: 1.0,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.0,
      autoRotateSpeedY: 0.9,
      autoRotateSpeedZ: 0.2,
      manualRotationX: 0.35,
      contrast: 1.5,
      cameraDistance: 3.3,
    },
    theme: 'green',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'spaceship',
    name: 'Retro Starfighter',
    description: 'Low-poly supersonic space interceptor with wing cannons',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'spaceship',
      scale: 1.1,
      flatShading: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.25,
      autoRotateSpeedY: 0.7,
      autoRotateSpeedZ: 0.15,
      manualRotationX: 0.3,
      edgeWeight: 0.6,
      contrast: 1.45,
    },
    theme: 'matrix',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'crystal',
    name: 'Diamond Crystal',
    description: 'Multi-faceted geometric icosahedron with specular glints',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'crystal',
      scale: 1.15,
      flatShading: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.45,
      autoRotateSpeedY: 0.55,
      autoRotateSpeedZ: 0.3,
      contrast: 1.7,
      specularIntensity: 1.8,
    },
    theme: 'monochrome',
    densityCharset: CHARSETS[2].chars,
  },
  {
    id: 'saturn',
    name: 'Saturn & Rings',
    description: 'Gas giant sphere encircled by wide orbital rings',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'saturn',
      scale: 1.0,
      doubleSided: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.15,
      autoRotateSpeedY: 0.5,
      autoRotateSpeedZ: 0.0,
      manualRotationX: 0.4,
      contrast: 1.4,
      cameraDistance: 3.4,
    },
    theme: 'amber',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'suzanne',
    name: 'Suzanne Monkey',
    description: 'Classic 3D modeling mascot polyhedron mesh',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'suzanne',
      scale: 1.15,
      flatShading: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'shaded',
      autoRotateSpeedX: 0.1,
      autoRotateSpeedY: 0.65,
      autoRotateSpeedZ: 0.0,
      manualRotationX: 0.15,
      contrast: 1.35,
    },
    theme: 'green',
    densityCharset: CHARSETS[0].chars,
  },
  {
    id: 'dome',
    name: 'Geodesic Wireframe',
    description: 'Complex geometric wireframe sphere and polyhedron vertices',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'dome',
      scale: 1.1,
      wireframe: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'wireframe',
      autoRotateSpeedX: 0.3,
      autoRotateSpeedY: 0.6,
      autoRotateSpeedZ: 0.15,
      contrast: 1.5,
    },
    theme: 'cyan',
    densityCharset: CHARSETS[4].chars,
  },
  {
    id: 'mobius',
    name: 'Möbius Strip',
    description: 'Single-sided continuous non-orientable topological surface',
    modelConfig: {
      ...DEFAULT_MODEL_CONFIG,
      modelId: 'mobius',
      scale: 1.05,
      doubleSided: true,
    },
    viewConfig: {
      ...DEFAULT_MODEL_VIEW_CONFIG,
      shadingMode: 'normals',
      autoRotateSpeedX: 0.4,
      autoRotateSpeedY: 0.5,
      autoRotateSpeedZ: 0.2,
      contrast: 1.4,
    },
    theme: 'monochrome',
    densityCharset: CHARSETS[0].chars,
  },
];
