import { Preset } from '../types/ascii';
import { DEFAULT_WAVE_PARAMS } from './math';

export const PRESETS: Preset[] = [
  // 1. Sine Wave Ripple
  {
    id: 'wave-parametric',
    name: 'Sine Wave Ripple',
    description: 'Radial expanding wave mixed with orthogonal directional swells',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.0,
      bias: 0.0,
      radialAmp: 0.6,
      radialFreq: 0.12,
      radialSpeed: 1.0,
      xAmp: 0.2,
      xFreq: 0.08,
      xSpeed: 0.5,
      yAmp: 0.2,
      yFreq: 0.08,
      ySpeed: 0.5,
    },
  },

  // 2. Spiral Vortex
  {
    id: 'spiral-vortex',
    name: 'Spiral Vortex',
    description: 'Rotating multi-arm spiral with inward angular velocity',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.2,
      aspectRatio: 0.55,
      contrast: 1.1,
      bias: 0.0,
      radialAmp: 0.4,
      radialFreq: 0.15,
      radialSpeed: 1.5,
      xAmp: 0.1,
      xFreq: 0.05,
      xSpeed: 0.5,
      yAmp: 0.0,
      spiralAmp: 0.7,
      spiralArms: 3,
      spiralSpeed: 2.0,
      spiralTwist: 0.1,
    },
  },

  // 3. Wormhole Tunnel
  {
    id: 'tunnel-hypnosis',
    name: 'Wormhole Tunnel',
    description: 'Non-linear inverse distance warp creating a 3D depth perception tunnel',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.0,
      bias: 0.0,
      radialAmp: 0.0,
      xAmp: 0.0,
      yAmp: 0.0,
      spiralAmp: 0.25,
      spiralArms: 5,
      spiralSpeed: 0.8,
      tunnelAmp: 0.8,
      tunnelPower: 42,
      tunnelSpeed: 1.5,
    },
  },

  // 4. Dual Interference Moiré
  {
    id: 'dual-interference',
    name: 'Dual Interference',
    description: 'Two frequency-locked emitters generating moiré interference patterns',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.2,
      bias: 0.0,
      radialAmp: 0.0,
      xAmp: 0.0,
      yAmp: 0.0,
      spiralAmp: 0.0,
      tunnelAmp: 0.0,
      dualEmitterAmp: 1.0,
      dualEmitterSpacing: 25,
      dualEmitterFreq: 0.18,
      dualEmitterSpeed: 2.0,
    },
  },

  // 5. Classic Plasma
  {
    id: 'hero-plasma',
    name: 'Classic Plasma',
    description: 'Organic flowing 4-component trigonometric field from portfolio hero',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.2,
      bias: 0.0,
      radialAmp: 0.25,
      radialFreq: 0.1,
      radialSpeed: 0.0,
      xAmp: 0.25,
      xFreq: 0.1,
      xSpeed: 1.0,
      yAmp: 0.25,
      yFreq: 0.1,
      ySpeed: 0.5,
      diagAmp: 0.25,
      diagFreq: 0.1,
      diagSpeed: 1.0,
    },
  },

  // 6. Concentric Rings
  {
    id: 'hero-rings',
    name: 'Pulsing Rings',
    description: 'Rotational dual ring harmonics with central glowing core',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.2,
      bias: -0.2,
      radialAmp: 0.0,
      xAmp: 0.0,
      yAmp: 0.0,
      tunnelAmp: 0.4,
      tunnelPower: 12,
      tunnelSpeed: 0.0,
      ringsAmp: 0.8,
      ringsRadius: 30,
      ringsSpeed: 1.5,
      ringsCount: 2,
      spiralAmp: 0.3,
      spiralArms: 2,
      spiralSpeed: 2.0,
    },
  },

  // 7. Solar System Orbits
  {
    id: 'hero-solar',
    name: 'Solar System Orbits',
    description: 'Pulsing central sun, orbital harmonics & starfield background',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.1,
      bias: -0.3,
      radialAmp: 0.4,
      radialFreq: 0.08,
      radialSpeed: 0.8,
      xAmp: 0.2,
      xFreq: 0.04,
      xSpeed: 0.8,
      yAmp: 0.2,
      yFreq: 0.04,
      ySpeed: 0.8,
      spiralAmp: 0.3,
      spiralArms: 1,
      spiralSpeed: 1.5,
      tunnelAmp: 0.5,
      tunnelPower: 15,
      tunnelSpeed: 0.0,
      ringsAmp: 0.4,
      ringsRadius: 42,
      ringsSpeed: 0.8,
      ringsCount: 3,
      starfieldIntensity: 0.25,
    },
  },

  // 8. Multi-Cell Ripples
  {
    id: 'hero-cells',
    name: 'Multi-Cell Ripples',
    description: 'Complex multi-harmonic pulsating wave interference',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.1,
      bias: -0.1,
      radialAmp: 0.5,
      radialFreq: 0.25,
      radialSpeed: 2.0,
      radial2Amp: 0.4,
      radial2Freq: 0.45,
      radial2Speed: 3.2,
      xAmp: 0.15,
      xFreq: 0.1,
      xSpeed: 1.0,
      yAmp: 0.15,
      yFreq: 0.1,
      ySpeed: 1.0,
    },
  },

  // 9. Cartesian Grid Swell
  {
    id: 'hero-grid',
    name: 'Matrix Grid Swell',
    description: 'Orthogonal drifting grid wave interference',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.0,
      bias: 0.0,
      radialAmp: 0.2,
      radialFreq: 0.05,
      radialSpeed: 1.0,
      xAmp: 0.4,
      xFreq: 0.15,
      xSpeed: 1.0,
      yAmp: 0.4,
      yFreq: 0.15,
      ySpeed: 1.0,
    },
  },

  // 10. Hypnotic Moiré
  {
    id: 'moire-field',
    name: 'Hypnotic Moiré',
    description: 'High frequency harmonic interference yielding optical illusion patterns',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.2,
      bias: 0.0,
      radialAmp: 0.5,
      radialFreq: 0.35,
      radialSpeed: 1.2,
      diagAmp: 0.3,
      diagFreq: 0.08,
      diagSpeed: 0.8,
      spiralAmp: 0.3,
      spiralArms: 6,
      spiralSpeed: 1.0,
    },
  },

  // 11. Cosmic Starfield
  {
    id: 'cosmic-starfield',
    name: 'Cosmic Starfield',
    description: 'Drifting interstellar nebula illuminated by glittering procedural starfields',
    type: 'parametric',
    params: {
      ...DEFAULT_WAVE_PARAMS,
      timeSpeed: 1.0,
      aspectRatio: 0.55,
      contrast: 1.15,
      bias: -0.05,
      radialAmp: 0.35,
      radialFreq: 0.08,
      radialSpeed: 0.8,
      spiralAmp: 0.25,
      spiralArms: 2,
      spiralSpeed: 0.6,
      spiralTwist: 0.12,
      starfieldIntensity: 0.9,
      starfieldDensity: 2.2,
      starfieldSpeed: 3.5,
      starfieldScale: 75,
    },
  },
];
